import { useLocalStorage } from './useLocalStorage';

export type Language = 'en' | 'hi' | 'mr';

const translations = {
  en: {
    // App
    appName: 'KaamTrack',
    tagline: 'Worker Attendance & Payment Tracker',
    home: 'Home',
    workers: 'Workers',
    scan: 'Scan',
    reports: 'Reports',
    settings: 'Settings',
    
    // Login
    chooseRole: 'How do you want to login?',
    ownerMalik: 'Owner / Malik',
    ownerDescription: 'Manage workers, attendance & payments',
    workerKamgar: 'Worker / Kamgar',
    workerDescription: 'View your attendance & earnings',
    ownerLogin: 'Owner Login',
    workerLogin: 'Worker Login',
    yourName: 'Your Name',
    enterName: 'Enter your name',
    phoneNumber: 'Phone Number',
    login: 'Login',
    noWorkersRegistered: 'No workers registered yet',
    askOwnerToAdd: 'Ask the owner to add you first',
    selectYourName: 'Select your name',
    logout: 'Logout',
    
    // Worker Dashboard
    myDashboard: 'My Dashboard',
    day: 'day',
    mySummary: 'My Summary',
    daysWorked: 'Days Worked',
    advances: 'Advances',
    recentAttendance: 'Recent Attendance',
    noAttendanceYet: 'No attendance records yet',
    
    // Home Page
    todayAttendance: "Today's Attendance",
    totalWorkers: 'Total Workers',
    present: 'Present',
    halfDay: 'Half Day',
    absent: 'Absent',
    quickActions: 'Quick Actions',
    todayQRCode: "Today's QR Code",
    scanQRForAttendance: 'Let workers scan for attendance',
    markAttendance: 'Mark Attendance',
    manualAttendance: 'Manual attendance marking',
    advancePayment: 'Advance / Payment',
    recordAdvance: 'Record advance or payment',
    workersSection: 'Workers',
    viewAll: 'View All',
    noWorkersYet: 'No workers yet',
    addWorker: 'Add Worker',
    
    // Workers Page
    searchWorkers: 'Search workers...',
    allTypes: 'All Types',
    
    // Scan Page
    attendanceQR: 'Attendance QR',
    scannerMode: 'Scanner Mode',
    ownerMode: 'Owner',
    workerMode: 'Worker',
    ownerModeDesc: 'Show QR code for workers to scan',
    workerModeDesc: 'Scan owner\'s QR code for attendance',
    showQR: 'Show QR Code',
    scanQR: 'Scan QR Code',
    
    // QR Scanner
    scanning: 'Scanning...',
    alignQRCode: 'Align the QR code within the frame',
    startCamera: 'Start Camera',
    stopCamera: 'Stop Camera',
    attendanceMarked: 'Attendance Marked!',
    yourAttendanceRecorded: 'Your attendance has been recorded for today',
    done: 'Done',
    scanFailed: 'Scan Failed',
    invalidQR: 'Invalid or expired QR code',
    tryAgain: 'Try Again',
    cameraError: 'Camera Error',
    cameraPermissionDenied: 'Camera permission denied. Please allow camera access.',
    
    // QR Display
    generateQR: 'Generate QR',
    generateTodayQR: "Generate today's QR",
    generateNewQR: 'Generate new QR',
    createTodayQR: "Create today's QR code",
    askWorkersToScan: 'Ask workers to scan this QR',
    validTime: 'Valid: 7 AM - 11 AM',
    validUntil: 'Valid until',
    showToWorkers: 'Show this QR code to workers for attendance',
    downloadQR: 'Download QR',
    
    // Reports
    summary: 'Summary',
    workerWise: 'Worker-wise',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    allTime: 'All Time',
    totalDaysWorked: 'Total Days Worked',
    totalEarnings: 'Total Earnings',
    advanceGiven: 'Advance Given',
    balanceDue: 'Balance Due',
    exportPDF: 'Export PDF',
    due: 'due',
    noDataAvailable: 'No data available for the selected period',
    
    // Settings
    appMode: 'App Mode',
    owner: 'Owner',
    worker: 'Worker',
    ownerDesc: 'Generate QR and manage attendance',
    workerDesc: 'Scan QR and view your attendance',
    dailyReminders: 'Daily Reminders',
    dailyAttendanceReminder: 'Daily Attendance Reminder',
    remindersActive: 'Reminders are active',
    remindersOff: 'Reminders are off',
    reminderTime: 'Reminder Time',
    testNotification: 'Test Notification',
    reminderDescription: 'Get reminded daily to mark attendance at your preferred time',
    general: 'General',
    language: 'Language',
    notifications: 'Notifications',
    remindersAlerts: 'Reminders & alerts',
    dataPrivacy: 'Data & Privacy',
    dataBackup: 'Data Backup',
    exportData: 'Export your data',
    deleteAllData: 'Delete All Data',
    removeAllRecords: 'Remove all workers & records',
    helpInfo: 'Help & Info',
    howToUse: 'How to use',
    guideFAQ: 'Guide & FAQs',
    about: 'About',
    appStats: 'App Stats',
    offlineReady: 'Offline Ready',
    madeWithLove: 'Made with ❤️ for daily-wage workers',
    
    // Worker Detail
    attendance: 'Attendance',
    payments: 'Payments',
    workType: 'Work Type',
    dailyRate: 'Daily Rate',
    balance: 'Balance',
    days: 'Days',
    thisMonthAttendance: 'This Month',
    addPayment: 'Add Payment',
    advance: 'Advance',
    payment: 'Payment',
    amount: 'Amount',
    enterAmount: 'Enter amount',
    note: 'Note',
    optional: 'optional',
    cancel: 'Cancel',
    save: 'Save',
    noAttendanceRecords: 'No attendance records yet',
    noPaymentRecords: 'No payment records yet',
    exportWorkerReport: 'Export Worker Report',
    
    // Add Worker
    addNewWorker: 'Add New Worker',
    name: 'Name',
    workerName: 'Worker name',
    selectWorkType: 'Select work type',
    construction: 'Construction',
    carpentry: 'Carpentry',
    painting: 'Painting',
    plumbing: 'Plumbing',
    electrical: 'Electrical',
    helper: 'Helper',
    driver: 'Driver',
    other: 'Other',
    perDay: 'per day',
    
    // Attendance
    attendanceActions: 'Attendance',
    markPresent: 'Present',
    markHalfDay: 'Half Day',
    markAbsent: 'Absent',
    
    // Common
    today: 'Today',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
  },
  hi: {
    // App
    appName: 'KaamTrack',
    tagline: 'कामगार हाज़िरी और भुगतान ट्रैकर',
    
    // Navigation
    home: 'होम',
    workers: 'कामगार',
    scan: 'स्कैन',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    
    // Login
    chooseRole: 'आप कैसे लॉगिन करना चाहते हैं?',
    ownerMalik: 'मालिक',
    ownerDescription: 'कामगार, हाज़िरी और पेमेंट मैनेज करें',
    workerKamgar: 'कामगार',
    workerDescription: 'अपनी हाज़िरी और कमाई देखें',
    ownerLogin: 'मालिक लॉगिन',
    workerLogin: 'कामगार लॉगिन',
    yourName: 'आपका नाम',
    enterName: 'अपना नाम दर्ज करें',
    phoneNumber: 'फोन नंबर',
    login: 'लॉगिन',
    noWorkersRegistered: 'अभी कोई कामगार रजिस्टर्ड नहीं',
    askOwnerToAdd: 'मालिक से पहले आपको जोड़ने को कहें',
    selectYourName: 'अपना नाम चुनें',
    logout: 'लॉगआउट',
    
    // Worker Dashboard
    myDashboard: 'मेरा डैशबोर्ड',
    day: 'दिन',
    mySummary: 'मेरा सारांश',
    daysWorked: 'काम के दिन',
    advances: 'एडवांस',
    recentAttendance: 'हाल की हाज़िरी',
    noAttendanceYet: 'अभी कोई हाज़िरी रिकॉर्ड नहीं',
    
    // Home Page
    todayAttendance: 'आज की हाज़िरी',
    totalWorkers: 'कुल कामगार',
    present: 'हाज़िर',
    halfDay: 'आधा दिन',
    absent: 'गैरहाज़िर',
    quickActions: 'त्वरित कार्य',
    todayQRCode: 'आज का QR कोड',
    scanQRForAttendance: 'कामगारों को हाज़िरी के लिए स्कैन दें',
    markAttendance: 'हाज़िरी भरें',
    manualAttendance: 'मैन्युअल हाज़िरी',
    advancePayment: 'एडवांस / पेमेंट',
    recordAdvance: 'एडवांस या पेमेंट दर्ज करें',
    workersSection: 'कामगार',
    viewAll: 'सभी देखें',
    noWorkersYet: 'अभी कोई कामगार नहीं',
    addWorker: 'कामगार जोड़ें',
    
    // Workers Page
    searchWorkers: 'कामगार खोजें...',
    allTypes: 'सभी प्रकार',
    
    // Scan Page
    attendanceQR: 'हाज़िरी QR',
    scannerMode: 'स्कैनर मोड',
    ownerMode: 'मालिक',
    workerMode: 'कामगार',
    ownerModeDesc: 'कामगारों को स्कैन के लिए QR दिखाएं',
    workerModeDesc: 'हाज़िरी के लिए मालिक का QR स्कैन करें',
    showQR: 'QR दिखाएं',
    scanQR: 'QR स्कैन करें',
    
    // QR Scanner
    scanning: 'स्कैन हो रहा है...',
    alignQRCode: 'QR कोड को फ्रेम में रखें',
    startCamera: 'कैमरा चालू करें',
    stopCamera: 'कैमरा बंद करें',
    attendanceMarked: 'हाज़िरी लगी!',
    yourAttendanceRecorded: 'आपकी आज की हाज़िरी दर्ज हो गई',
    done: 'ठीक है',
    scanFailed: 'स्कैन विफल',
    invalidQR: 'अमान्य या समाप्त QR कोड',
    tryAgain: 'फिर से कोशिश करें',
    cameraError: 'कैमरा त्रुटि',
    cameraPermissionDenied: 'कैमरा अनुमति अस्वीकृत। कृपया कैमरा एक्सेस दें।',
    
    // QR Display
    generateQR: 'QR बनाएं',
    generateTodayQR: 'आज का QR बनाएं',
    generateNewQR: 'नया QR बनाएं',
    createTodayQR: 'आज का QR कोड बनाएं',
    askWorkersToScan: 'कामगारों को यह QR स्कैन करने को कहें',
    validTime: 'वैध: सुबह 7 - 11 बजे',
    validUntil: 'वैध समय तक',
    showToWorkers: 'यह QR कोड कामगारों को हाज़िरी के लिए दिखाएं',
    downloadQR: 'QR डाउनलोड करें',
    
    // Reports
    summary: 'सारांश',
    workerWise: 'कामगार-वार',
    thisWeek: 'इस हफ्ते',
    thisMonth: 'इस महीने',
    allTime: 'पूरा समय',
    totalDaysWorked: 'कुल कार्य दिवस',
    totalEarnings: 'कुल कमाई',
    advanceGiven: 'दी गई एडवांस',
    balanceDue: 'बकाया',
    exportPDF: 'PDF निर्यात करें',
    due: 'बकाया',
    noDataAvailable: 'चयनित अवधि के लिए कोई डेटा नहीं',
    
    // Settings
    appMode: 'ऐप मोड',
    owner: 'मालिक',
    worker: 'कामगार',
    ownerDesc: 'QR बनाएं और हाज़िरी देखें',
    workerDesc: 'QR स्कैन करें और अपनी हाज़िरी देखें',
    dailyReminders: 'दैनिक रिमाइंडर',
    dailyAttendanceReminder: 'दैनिक हाज़िरी रिमाइंडर',
    remindersActive: 'रिमाइंडर चालू हैं',
    remindersOff: 'रिमाइंडर बंद हैं',
    reminderTime: 'रिमाइंडर समय',
    testNotification: 'टेस्ट नोटिफिकेशन',
    reminderDescription: 'अपने पसंदीदा समय पर हाज़िरी के लिए रोज़ाना रिमाइंडर पाएं',
    general: 'सामान्य',
    language: 'भाषा',
    notifications: 'नोटिफिकेशन',
    remindersAlerts: 'रिमाइंडर और अलर्ट',
    dataPrivacy: 'डेटा और गोपनीयता',
    dataBackup: 'डेटा बैकअप',
    exportData: 'अपना डेटा निर्यात करें',
    deleteAllData: 'सभी डेटा हटाएं',
    removeAllRecords: 'सभी कामगार और रिकॉर्ड हटाएं',
    helpInfo: 'मदद और जानकारी',
    howToUse: 'कैसे उपयोग करें',
    guideFAQ: 'गाइड और FAQ',
    about: 'ऐप के बारे में',
    appStats: 'ऐप आंकड़े',
    offlineReady: 'ऑफलाइन तैयार',
    madeWithLove: 'दैनिक मज़दूरों के लिए ❤️ से बनाया',
    
    // Worker Detail
    attendance: 'हाज़िरी',
    payments: 'पेमेंट',
    workType: 'काम का प्रकार',
    dailyRate: 'दैनिक दर',
    balance: 'बकाया',
    days: 'दिन',
    thisMonthAttendance: 'इस महीने',
    addPayment: 'पेमेंट जोड़ें',
    advance: 'एडवांस',
    payment: 'पेमेंट',
    amount: 'राशि',
    enterAmount: 'राशि दर्ज करें',
    note: 'नोट',
    optional: 'वैकल्पिक',
    cancel: 'रद्द करें',
    save: 'सेव करें',
    noAttendanceRecords: 'अभी कोई हाज़िरी रिकॉर्ड नहीं',
    noPaymentRecords: 'अभी कोई पेमेंट रिकॉर्ड नहीं',
    exportWorkerReport: 'कामगार रिपोर्ट निर्यात करें',
    
    // Add Worker
    addNewWorker: 'नया कामगार जोड़ें',
    name: 'नाम',
    workerName: 'कामगार का नाम',
    selectWorkType: 'काम का प्रकार चुनें',
    construction: 'निर्माण',
    carpentry: 'बढ़ईगीरी',
    painting: 'पेंटिंग',
    plumbing: 'प्लंबिंग',
    electrical: 'इलेक्ट्रिकल',
    helper: 'हेल्पर',
    driver: 'ड्राइवर',
    other: 'अन्य',
    perDay: 'प्रति दिन',
    
    // Attendance
    attendanceActions: 'हाज़िरी',
    markPresent: 'हाज़िर',
    markHalfDay: 'आधा दिन',
    markAbsent: 'गैरहाज़िर',
    
    // Common
    today: 'आज',
    close: 'बंद करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
  },
  mr: {
    // App
    appName: 'KaamTrack',
    tagline: 'कामगार हजेरी आणि पेमेंट ट्रॅकर',
    
    // Navigation
    home: 'होम',
    workers: 'कामगार',
    scan: 'स्कॅन',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्ज',
    
    // Login
    chooseRole: 'तुम्ही कसे लॉगिन करू इच्छिता?',
    ownerMalik: 'मालक',
    ownerDescription: 'कामगार, हजेरी आणि पेमेंट व्यवस्थापित करा',
    workerKamgar: 'कामगार',
    workerDescription: 'तुमची हजेरी आणि कमाई पहा',
    ownerLogin: 'मालक लॉगिन',
    workerLogin: 'कामगार लॉगिन',
    yourName: 'तुमचे नाव',
    enterName: 'तुमचे नाव टाका',
    phoneNumber: 'फोन नंबर',
    login: 'लॉगिन',
    noWorkersRegistered: 'अजून कोणी कामगार नोंदणी केलेला नाही',
    askOwnerToAdd: 'मालकाला आधी तुम्हाला जोडायला सांगा',
    selectYourName: 'तुमचे नाव निवडा',
    logout: 'लॉगआउट',
    
    // Worker Dashboard
    myDashboard: 'माझा डॅशबोर्ड',
    day: 'दिवस',
    mySummary: 'माझा सारांश',
    daysWorked: 'काम केलेले दिवस',
    advances: 'अडव्हान्स',
    recentAttendance: 'अलीकडील हजेरी',
    noAttendanceYet: 'अजून हजेरी नोंद नाही',
    
    // Home Page
    todayAttendance: 'आजची हजेरी',
    totalWorkers: 'एकूण कामगार',
    present: 'हजर',
    halfDay: 'अर्धा दिवस',
    absent: 'गैरहजर',
    quickActions: 'जलद क्रिया',
    todayQRCode: 'आजचा QR कोड',
    scanQRForAttendance: 'कामगारांना हजेरीसाठी स्कॅन द्या',
    markAttendance: 'हजेरी भरा',
    manualAttendance: 'मॅन्युअल हजेरी',
    advancePayment: 'अडव्हान्स / पेमेंट',
    recordAdvance: 'अडव्हान्स किंवा पेमेंट नोंदवा',
    workersSection: 'कामगार',
    viewAll: 'सर्व पहा',
    noWorkersYet: 'अजून कामगार नाहीत',
    addWorker: 'कामगार जोडा',
    
    // Workers Page
    searchWorkers: 'कामगार शोधा...',
    allTypes: 'सर्व प्रकार',
    
    // Scan Page
    attendanceQR: 'हजेरी QR',
    scannerMode: 'स्कॅनर मोड',
    ownerMode: 'मालक',
    workerMode: 'कामगार',
    ownerModeDesc: 'कामगारांना स्कॅनसाठी QR दाखवा',
    workerModeDesc: 'हजेरीसाठी मालकाचा QR स्कॅन करा',
    showQR: 'QR दाखवा',
    scanQR: 'QR स्कॅन करा',
    
    // QR Scanner
    scanning: 'स्कॅन होत आहे...',
    alignQRCode: 'QR कोड फ्रेममध्ये ठेवा',
    startCamera: 'कॅमेरा सुरू करा',
    stopCamera: 'कॅमेरा बंद करा',
    attendanceMarked: 'हजेरी लागली!',
    yourAttendanceRecorded: 'तुमची आजची हजेरी नोंदवली गेली',
    done: 'ठीक आहे',
    scanFailed: 'स्कॅन अयशस्वी',
    invalidQR: 'अवैध किंवा कालबाह्य QR कोड',
    tryAgain: 'पुन्हा प्रयत्न करा',
    cameraError: 'कॅमेरा त्रुटी',
    cameraPermissionDenied: 'कॅमेरा परवानगी नाकारली. कृपया कॅमेरा ॲक्सेस द्या.',
    
    // QR Display
    generateQR: 'QR बनवा',
    generateTodayQR: 'आजचा QR बनवा',
    generateNewQR: 'नवीन QR बनवा',
    createTodayQR: 'आजचा QR कोड तयार करा',
    askWorkersToScan: 'कामगारांना हा QR स्कॅन करायला सांगा',
    validTime: 'वैध: सकाळी ७ - ११ वाजता',
    validUntil: 'वैध वेळेपर्यंत',
    showToWorkers: 'हा QR कोड कामगारांना हजेरीसाठी दाखवा',
    downloadQR: 'QR डाउनलोड करा',
    
    // Reports
    summary: 'सारांश',
    workerWise: 'कामगार-निहाय',
    thisWeek: 'या आठवड्यात',
    thisMonth: 'या महिन्यात',
    allTime: 'संपूर्ण कालावधी',
    totalDaysWorked: 'एकूण कार्य दिवस',
    totalEarnings: 'एकूण कमाई',
    advanceGiven: 'दिलेला अडव्हान्स',
    balanceDue: 'बाकी रक्कम',
    exportPDF: 'PDF निर्यात करा',
    due: 'बाकी',
    noDataAvailable: 'निवडलेल्या कालावधीसाठी डेटा नाही',
    
    // Settings
    appMode: 'ॲप मोड',
    owner: 'मालक',
    worker: 'कामगार',
    ownerDesc: 'QR बनवा आणि हजेरी पहा',
    workerDesc: 'QR स्कॅन करा आणि तुमची हजेरी पहा',
    dailyReminders: 'दैनिक रिमाइंडर',
    dailyAttendanceReminder: 'दैनिक हजेरी रिमाइंडर',
    remindersActive: 'रिमाइंडर चालू आहेत',
    remindersOff: 'रिमाइंडर बंद आहेत',
    reminderTime: 'रिमाइंडर वेळ',
    testNotification: 'टेस्ट नोटिफिकेशन',
    reminderDescription: 'तुमच्या आवडत्या वेळी हजेरीसाठी दररोज रिमाइंडर मिळवा',
    general: 'सामान्य',
    language: 'भाषा',
    notifications: 'नोटिफिकेशन',
    remindersAlerts: 'रिमाइंडर आणि अलर्ट',
    dataPrivacy: 'डेटा आणि गोपनीयता',
    dataBackup: 'डेटा बॅकअप',
    exportData: 'तुमचा डेटा निर्यात करा',
    deleteAllData: 'सर्व डेटा हटवा',
    removeAllRecords: 'सर्व कामगार आणि रेकॉर्ड हटवा',
    helpInfo: 'मदत आणि माहिती',
    howToUse: 'कसे वापरावे',
    guideFAQ: 'मार्गदर्शक आणि FAQ',
    about: 'ॲप बद्दल',
    appStats: 'ॲप आकडेवारी',
    offlineReady: 'ऑफलाइन तयार',
    madeWithLove: 'दैनिक मजुरांसाठी ❤️ ने बनवले',
    
    // Worker Detail
    attendance: 'हजेरी',
    payments: 'पेमेंट',
    workType: 'कामाचा प्रकार',
    dailyRate: 'दैनिक दर',
    balance: 'बाकी',
    days: 'दिवस',
    thisMonthAttendance: 'या महिन्यात',
    addPayment: 'पेमेंट जोडा',
    advance: 'अडव्हान्स',
    payment: 'पेमेंट',
    amount: 'रक्कम',
    enterAmount: 'रक्कम टाका',
    note: 'नोट',
    optional: 'ऐच्छिक',
    cancel: 'रद्द करा',
    save: 'सेव्ह करा',
    noAttendanceRecords: 'अजून हजेरी रेकॉर्ड नाही',
    noPaymentRecords: 'अजून पेमेंट रेकॉर्ड नाही',
    exportWorkerReport: 'कामगार रिपोर्ट निर्यात करा',
    
    // Add Worker
    addNewWorker: 'नवीन कामगार जोडा',
    name: 'नाव',
    workerName: 'कामगाराचे नाव',
    selectWorkType: 'कामाचा प्रकार निवडा',
    construction: 'बांधकाम',
    carpentry: 'सुतारकाम',
    painting: 'पेंटिंग',
    plumbing: 'प्लंबिंग',
    electrical: 'इलेक्ट्रिकल',
    helper: 'मदतनीस',
    driver: 'ड्रायव्हर',
    other: 'इतर',
    perDay: 'प्रति दिवस',
    
    // Attendance
    attendanceActions: 'हजेरी',
    markPresent: 'हजर',
    markHalfDay: 'अर्धा दिवस',
    markAbsent: 'गैरहजर',
    
    // Common
    today: 'आज',
    close: 'बंद करा',
    delete: 'हटवा',
    edit: 'संपादित करा',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function useLanguage() {
  const [language, setLanguage] = useLocalStorage<Language>('kaamtrack-language', 'en');

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const languageNames: Record<Language, string> = {
    en: 'English',
    hi: 'Hindi',
    mr: 'Marathi',
  };

  const languageNamesNative: Record<Language, string> = {
    en: 'English',
    hi: 'हिंदी',
    mr: 'मराठी',
  };

  return {
    language,
    setLanguage,
    t,
    languageNames,
    languageNamesNative,
    availableLanguages: ['en', 'hi', 'mr'] as Language[],
  };
}
