import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Worker, AttendanceRecord, PaymentRecord } from '@/types';
import { WORK_TYPES } from '@/types';

interface WorkerStats {
  presentDays: number;
  halfDays: number;
  totalEarnings: number;
  totalAdvances: number;
  totalPaid: number;
  balance: number;
}

interface ExportData {
  workers: Worker[];
  attendance: AttendanceRecord[];
  payments: PaymentRecord[];
  getWorkerStats: (workerId: string) => WorkerStats | null;
}

export function generatePDFReport(data: ExportData, period: 'week' | 'month' = 'month') {
  const { workers, attendance, getWorkerStats } = data;
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(22);
  doc.setTextColor(15, 118, 110); // Primary color
  doc.text('Kaam Hisab Report', pageWidth / 2, 20, { align: 'center' });
  
  // Subtitle
  doc.setFontSize(12);
  doc.setTextColor(100);
  const periodText = period === 'week' ? 'Weekly Report' : 'Monthly Report';
  const dateText = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
  doc.text(`${periodText} - Generated on ${dateText}`, pageWidth / 2, 28, { align: 'center' });
  
  // Summary Section
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text('Summary', 14, 42);
  
  // Calculate totals
  let totalEarnings = 0;
  let totalAdvances = 0;
  let totalBalance = 0;
  let totalPresentDays = 0;
  
  workers.forEach(worker => {
    const stats = getWorkerStats(worker.id);
    if (stats) {
      totalEarnings += stats.totalEarnings;
      totalAdvances += stats.totalAdvances;
      totalBalance += stats.balance;
      totalPresentDays += stats.presentDays + (stats.halfDays * 0.5);
    }
  });
  
  // Summary table
  autoTable(doc, {
    startY: 46,
    head: [['Metric', 'Value']],
    body: [
      ['Total Workers', workers.length.toString()],
      ['Total Working Days', totalPresentDays.toString()],
      ['Total Earnings', `₹${totalEarnings.toLocaleString('en-IN')}`],
      ['Total Advances', `₹${totalAdvances.toLocaleString('en-IN')}`],
      ['Total Balance', `₹${totalBalance.toLocaleString('en-IN')}`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [15, 118, 110] },
    styles: { fontSize: 10 },
    columnStyles: {
      0: { fontStyle: 'bold' },
      1: { halign: 'right' },
    },
  });
  
  // Worker Details Section
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.text('Worker-wise Details', 14, finalY);
  
  // Worker details table
  const workerRows = workers.map(worker => {
    const stats = getWorkerStats(worker.id);
    const workType = WORK_TYPES.find(t => t.value === worker.workType);
    return [
      worker.name,
      workType?.label || worker.workType,
      `₹${worker.dailyRate}`,
      stats ? (stats.presentDays + stats.halfDays * 0.5).toString() : '0',
      stats ? `₹${stats.totalEarnings.toLocaleString('en-IN')}` : '₹0',
      stats ? `₹${stats.totalAdvances.toLocaleString('en-IN')}` : '₹0',
      stats ? `₹${stats.balance.toLocaleString('en-IN')}` : '₹0',
    ];
  });
  
  autoTable(doc, {
    startY: finalY + 4,
    head: [['Name', 'Work Type', 'Daily Rate', 'Days', 'Earnings', 'Advances', 'Balance']],
    body: workerRows,
    theme: 'striped',
    headStyles: { fillColor: [15, 118, 110], fontSize: 9 },
    styles: { fontSize: 8 },
    columnStyles: {
      2: { halign: 'right' },
      3: { halign: 'center' },
      4: { halign: 'right' },
      5: { halign: 'right' },
      6: { halign: 'right' },
    },
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by Kaam Hisab App`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  // Save
  const fileName = `kaam-hisab-report-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
  
  return fileName;
}

export function generateWorkerPDFReport(
  worker: Worker,
  attendance: AttendanceRecord[],
  payments: PaymentRecord[],
  stats: WorkerStats | null
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(15, 118, 110);
  doc.text(worker.name, pageWidth / 2, 20, { align: 'center' });
  
  // Subtitle
  doc.setFontSize(11);
  doc.setTextColor(100);
  const workType = WORK_TYPES.find(t => t.value === worker.workType);
  doc.text(`${workType?.label || worker.workType} - ₹${worker.dailyRate}/day`, pageWidth / 2, 28, { align: 'center' });
  doc.text(`Worker ID: ${worker.qrId}`, pageWidth / 2, 34, { align: 'center' });
  
  // Summary
  if (stats) {
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text('Payment Summary', 14, 48);
    
    autoTable(doc, {
      startY: 52,
      head: [['Description', 'Amount']],
      body: [
        ['Total Working Days', `${stats.presentDays + stats.halfDays * 0.5} days`],
        ['Total Earnings', `₹${stats.totalEarnings.toLocaleString('en-IN')}`],
        ['Advances Taken', `₹${stats.totalAdvances.toLocaleString('en-IN')}`],
        ['Payments Received', `₹${stats.totalPaid.toLocaleString('en-IN')}`],
        ['Balance Due', `₹${stats.balance.toLocaleString('en-IN')}`],
      ],
      theme: 'grid',
      headStyles: { fillColor: [15, 118, 110] },
      styles: { fontSize: 10 },
      columnStyles: {
        0: { fontStyle: 'bold' },
        1: { halign: 'right' },
      },
    });
  }
  
  // Attendance History
  const attendanceY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.text('Recent Attendance', 14, attendanceY);
  
  const attendanceRows = attendance
    .slice(-20)
    .reverse()
    .map(record => [
      new Date(record.date).toLocaleDateString('en-IN', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
      }),
      record.status === 'present' ? 'Present' : record.status === 'half-day' ? 'Half Day' : 'Absent',
      record.markedVia === 'qr' ? 'QR Scan' : 'Manual',
    ]);
  
  autoTable(doc, {
    startY: attendanceY + 4,
    head: [['Date', 'Status', 'Marked Via']],
    body: attendanceRows.length > 0 ? attendanceRows : [['No records', '-', '-']],
    theme: 'striped',
    headStyles: { fillColor: [15, 118, 110] },
    styles: { fontSize: 9 },
  });
  
  // Payment History
  const paymentY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.text('Payment History', 14, paymentY);
  
  const paymentRows = payments
    .slice(-15)
    .reverse()
    .map(payment => [
      new Date(payment.date).toLocaleDateString('en-IN', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
      }),
      payment.type === 'advance' ? 'Advance' : 'Payment',
      `₹${payment.amount.toLocaleString('en-IN')}`,
      payment.note || '-',
    ]);
  
  autoTable(doc, {
    startY: paymentY + 4,
    head: [['Date', 'Type', 'Amount', 'Note']],
    body: paymentRows.length > 0 ? paymentRows : [['No records', '-', '-', '-']],
    theme: 'striped',
    headStyles: { fillColor: [15, 118, 110] },
    styles: { fontSize: 9 },
    columnStyles: {
      2: { halign: 'right' },
    },
  });
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Generated on ${new Date().toLocaleDateString('en-IN')} - Kaam Hisab App`,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: 'center' }
  );
  
  // Save
  const fileName = `${worker.name.replace(/\s+/g, '-')}-report-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
  
  return fileName;
}
